# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import client_pb2 as client__pb2


class SecretStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreSecret = channel.unary_unary(
                '/SecretStore/StoreSecret',
                request_serializer=client__pb2.StoreRequest.SerializeToString,
                response_deserializer=client__pb2.StoreResponse.FromString,
                )
        self.RetrieveSecret = channel.unary_unary(
                '/SecretStore/RetrieveSecret',
                request_serializer=client__pb2.RetrieveRequest.SerializeToString,
                response_deserializer=client__pb2.RetrieveResponse.FromString,
                )


class SecretStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecretStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreSecret,
                    request_deserializer=client__pb2.StoreRequest.FromString,
                    response_serializer=client__pb2.StoreResponse.SerializeToString,
            ),
            'RetrieveSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveSecret,
                    request_deserializer=client__pb2.RetrieveRequest.FromString,
                    response_serializer=client__pb2.RetrieveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SecretStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SecretStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SecretStore/StoreSecret',
            client__pb2.StoreRequest.SerializeToString,
            client__pb2.StoreResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SecretStore/RetrieveSecret',
            client__pb2.RetrieveRequest.SerializeToString,
            client__pb2.RetrieveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
