# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: client.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import client_pb2 as client_pb2


class SecretStoreBase(abc.ABC):

    @abc.abstractmethod
    async def StoreSecret(self, stream: 'grpclib.server.Stream[client_pb2.StoreRequest, client_pb2.StoreResponse]') -> None:
        pass

    @abc.abstractmethod
    async def RetrieveSecret(self, stream: 'grpclib.server.Stream[client_pb2.RetrieveRequest, client_pb2.RetrieveResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/SecretStore/StoreSecret': grpclib.const.Handler(
                self.StoreSecret,
                grpclib.const.Cardinality.UNARY_UNARY,
                client_pb2.StoreRequest,
                client_pb2.StoreResponse,
            ),
            '/SecretStore/RetrieveSecret': grpclib.const.Handler(
                self.RetrieveSecret,
                grpclib.const.Cardinality.UNARY_UNARY,
                client_pb2.RetrieveRequest,
                client_pb2.RetrieveResponse,
            ),
        }


class SecretStoreStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.StoreSecret = grpclib.client.UnaryUnaryMethod(
            channel,
            '/SecretStore/StoreSecret',
            client_pb2.StoreRequest,
            client_pb2.StoreResponse,
        )
        self.RetrieveSecret = grpclib.client.UnaryUnaryMethod(
            channel,
            '/SecretStore/RetrieveSecret',
            client_pb2.RetrieveRequest,
            client_pb2.RetrieveResponse,
        )
